name: quality check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup project with .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/ApiQueryLanguageTests.sln
    - name: Code quality check
      run: dotnet format -v d ./src/ApiQueryLanguageTests.sln --verify-no-changes
    - name: Test
      run: dotnet test ./src/ApiQueryLanguageTests/ApiQueryLanguageTests.csproj
